language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
 - pip install coverage
 - pip install coveralls

script: coverage run -m unittest

after_success:
  coverage report
  coveralls